language: python
python:
  - 3.3
  - 3.4

install: pip install -r requirements.txt
script:
  # Lint
  - flake8 GDBump.py
  - flake8 constants.py
  - flake8 setup.py
  - flake8 ./tests
  - pep257 GDBump.py --explain
  - pep257 constants.py --explain
  - pep257 setup.py --explain

  # Run unit tests
  - python runtests.py
